reef-pi/reef-pi

- Makefile
- commands/log.go
- commands/main.go
- config.go
- modules/camera.go
- modules/controller.go
- modules/pump.go
- webui/auth.go
- Toggle log color output based on tty presence
- Always build arm binaries
- Rename recirculation pump as power head
> (chore)Fixes

- assets/js/reefer.js
- commands/main.go
- examples/config.yml
- templates/home.html
- webui/server.go
- Add sample config for dev environment
- Make reefer runnable without auth. 
- Add mock UI for devices
> Device mockup

- assets/jsx/electronics.jsx
- assets/jsx/outlets.jsx
- controller/raspi/api.go
- controller/raspi/board.go
- controller/raspi/main.go
- controller/raspi/outlets.go
- controller/types.go
- webui/api.go
- webui/auth.go
- webui/configure.go
- webui/device.go
- webui/info.go
- webui/lighting.go
- webui/server.go
- Allow configuring board pin layout (Pi, 8 channel relay, pca9645 & l293d)
- Allow configuring 6 110 V outlets.
> (feat)Board api

- assets/jsx/connection.jsx
- assets/jsx/equipment.jsx
- assets/jsx/equipments.jsx
- assets/jsx/outlets.jsx
- controller/job.go
- controller/outlet.go
- controller/raspi/api.go
- controller/raspi/job.go
- controller/raspi/main.go
- controller/raspi/outlets.go
- controller/raspi/pwm.go
- controller/store.go
- controller/structs.go
- controller/types.go
- package.json
- webui/api.go
- webui/job.go
- webui/outlet.go
> (chore)remove connection type. move run logic to job

- Makefile
- commands/main.go
- controller/config.go
- controller/controller.go
- controller/pid.go
- controller/pid_test.go
- controller/state.go
- controller/telemetry.go
- controller/telemetry_test.go
- controller/temperature.go
- doc/config.yml
> Add initial PID implementation & adafruit.io based

- .travis.yml
- api/api.go
- controller/config.go
- controller/dev_mode.go
- controller/lighting.go
- controller/lighting/lighting.go
- controller/pwm.go
- controller/state.go
- jsx/equipment.jsx
- jsx/led_channel.jsx
- jsx/lighting.jsx
- More error logging for failed api requests
- Support arbitrary led channels
- DevMode I2C bus stubbed driver
> (feat)arbitrary led channels

- controller/lighting.go
set pwm value to 0 when calculated value is below minimum threshold. …and to max threshold when its above max threshold
> (bug)dont skip pwm values when threshold is breached

- api/admin.go
- api/api.go
- api/info.go
- api/info_test.go
- api/server.go
- build/reef-pi.yml
- jsx/admin.jsx
- jsx/dashboard.jsx
- jsx/temperature.jsx
- Allow reef-pi controller to shutdown and reboot raspberry pi via web UI
> (feat)Admin API & UI

- controller/temperature/api.go
- controller/temperature/controller.go
- jsx/camera.jsx
- jsx/main_panel.jsx
- jsx/temperature.jsx
= and dont show image if no capture has been made
> (chore)show time in temperature chart 

- jsx/ato.jsx
- jsx/camera.jsx
- jsx/equipment.jsx
- jsx/led_channel.jsx
- jsx/light.jsx
- jsx/lighting.jsx
- jsx/temperature.jsx
add spacing between equipment name and on/off action.
dont updated fixed lighting on every slide move
change light  update button color when data changes
clean light ui by removing border and placing horizontal line instead
> (chore)ighting ui style cleanup

- controller/ato/ato.go
- controller/temperature/controller.go
- controller/utils/telemetry.go
- controller/utils/telemetry_test.go
- jsx/ato.jsx
- jsx/camera.jsx
- jsx/settings.jsx
- jsx/telemetry.jsx
- jsx/temperature.jsx
- Assign default pin configuration to ato & temperature subsystem
- Setting update button inside system tab will have color indicating update required or not
- Replace default feed name in telemetry with prefix
> (chore)Default pins

- controller/capabilities.go
- controller/controller.go
- controller/doser/api.go
- controller/doser/controller.go
- controller/doser/doser.go
- controller/settings.go
- controller/timer/controller.go
- controller/timer/job.go
- controller/timer/runner.go
- jsx/common.jsx
- jsx/doser.jsx
- jsx/equipment.jsx
- jsx/equipments.jsx
- jsx/lighting.jsx
- jsx/settings.jsx
- jsx/timer.jsx
- jsx/timers.jsx
- WIP: Dosing UI and API, stubbed controller
- Show equipment & timer details in UI
- Timer validation
- Common jsx class
> (feat)Doser

- controller/ato/ato.go
- controller/lighting/controller.go
- controller/temperature/controller.go
- controller/utils/telemetry.go
- jsx/settings.jsx
- jsx/telemetry.jsx
- Add UI validation for adafruit token and user
- Auto create adafruit.io feed
> (chore)Telemetry validation

- README.md
- controller/connectors/outlet.go
- jsx/equipment.jsx
- jsx/outlets.jsx
Outlets can be configured to have reverse effect, when enabled, will reverse the digital signal (0 to turn on and 1 to turn off) to support relay configured as normally open
> (feat)Relay configuration

- controller/ato/ato.go
- controller/controller.go
- controller/equipments/controller.go
- controller/equipments/equipment.go
- controller/temperature/controller.go
- controller/timer/controller.go
- controller/timer/job.go
- jsx/outlets.jsx
- jsx/select_equipment.jsx
- Check if equipment is in use across timer, ato or temperature before deletion
> (chore)Equipment validation

- controller/capabilities.go
- controller/capabilities_test.go
- controller/health.go
- controller/reef_pi.go
- controller/settings.go
- controller/utils/mailer.go
- jsx/capabilities.jsx
- jsx/configuration.jsx
- jsx/main_panel.jsx
- jsx/settings.jsx
- [chore] rename system tab to configuration
- [chore] move capability into its own sub structure
- [fest] add library method to send email
> (feat)Update cap

- controller/system/api.go
- controller/system/display.go
- jsx/dashboard.jsx
- jsx/display.jsx
- jsx/main_panel.jsx
- jsx/settings.jsx
- jsx/temperature.jsx
- jsx/temperature_chart.jsx
- Move temperature chart in its own component
- Show temperature chart in dashboard
- Improve display management UI
- refactor display api response structure
- Fix inconsistent ui in temperature module
> (chore)Temp dash

- controller/capabilities.go
- jsx/dashboard.jsx
- jsx/equipment_chart.jsx
- jsx/light_chart.jsx
- Add chart for equipment
- Add chart for lights
- Ensure equipment and timer tabs are placed next to each other
> (feat)More charts

- controller/temperature/api.go
- controller/temperature/control.go
- controller/temperature/controller.go
- jsx/temperature_chart.jsx
- Remove redundant equipment existence check
- Add api endpoint for getting equipment usage
- Add circular buffer based usage statistics gathering
> (feat)Temperature usage

- .travis.yml
- controller/reef_pi.go
- controller/settings.go
- jsx/settings.jsx
- Let user allow enabling/disabling heart beat.
> (feat)Health control

- controller/ato/api.go
- controller/ato/ato.go
- controller/ato/sensor.go
- controller/ato/usage.go
- controller/temperature/api.go
- controller/temperature/control.go
- controller/utils/http_json.go
- jsx/ato.jsx
- jsx/ato_chart.jsx
- jsx/dashboard.jsx
- jsx/equipment_chart.jsx
- jsx/temperature_chart.jsx
- Fix temperature usage logic
- auto update charts
- move common usage api code to utils library
- add ato pump usage chart
-
> (feat)Ato chart

- controller/ato/sensor.go
- controller/capabilities.go
- jsx/ato_chart.jsx
- jsx/dashboard.jsx
- jsx/equipment_chart.jsx
- jsx/light_chart.jsx
- jsx/temperature_chart.jsx
- ATO sensor will give random reads when run in dev mode instead of fixed 1
- Better colors for chart, more compact layout
> (chore)Better style for charts 

- controller/health.go
- jsx/ato_chart.jsx
- jsx/capabilities.jsx
- jsx/dashboard.jsx
- jsx/display.jsx
- jsx/health_chart.jsx
- jsx/light_chart.jsx
- jsx/settings.jsx
- jsx/temperature.jsx
- jsx/temperature_chart.jsx
- jsx/temperature_reading.jsx
- jsx reusable functions
- health chart (cpu & memory)
- minute level temperature reading chart
> (feat) health chart

- controller/health.go
- controller/lighting/controller.go
- controller/reef_pi.go
- controller/settings.go
- controller/temperature/config.go
- controller/temperature/controller.go
- controller/utils/mailer.go
- controller/utils/telemetry.go
- controller/utils/telemetry_test.go
- controller/utils/test_helpers.go
- jsx/capabilities.jsx
- jsx/equipment_chart.jsx
- jsx/health_notify.jsx
- jsx/settings.jsx
- jsx/temperature.jsx
- jsx/temperature_chart.jsx
- jsx/temperature_reading.jsx
- BUG - multi channel manual mode pwm setting
- FEAT - health check alert logic
- FEAT - temperature out of range alert logic
- CHORE - Temperature charts are ranged to 76-82F
> (but)Multiple channel manual pwm mode fix

- controller/reef_pi.go
- controller/utils/mailer.go
- jsx/health_notify.jsx
Integrate email notifier with main controller. If mailer config available configure email notifier, else use noop notifier
> (chore)Email notifier

- controller/timer/controller.go
- controller/timer/job.go
- reusing cron instance causes multiple trigger
> (bug)fix cron scheduling issue

- controller/equipments/controller.go
- jsx/telemetry/adafruit_io.jsx
sync equipment on startup
adafruit io settings labels should reflect original website labels
> (bug)Sync equipment on startup

- controller/timer/api_test.go
- controller/timer/controller.go
- controller/timer/job.go
- controller/timer/reminder.go
- controller/timer/runner.go
- jsx/timer.jsx
- jsx/timers.jsx
- jsx/timers/cron.jsx
- jsx/timers/equipment.jsx
- jsx/timers/reminder.jsx
- Add reminder target for timer sub-system
- Allow equipment action to be reversed after certain duration
> (feat)add support for reminder under timer sub system

- commands/main.go
- controller/api.go
- controller/ato/ato.go
- controller/settings.go
Allow serving API requests over https. 
Fix sigterm based service restart
> (feat)Https

- controller/api.go
- controller/utils/tls.go
- Auto generate tls key and cert when https is configured but certs are not exist
> (feat)auto generate tls key

- controller/timer/job.go
- controller/timer/old.go
Auto migrate 1.0 style timer jobs to newer format
> (bug)try updating old jobs if loading fails

- Makefile
- controller/doser/controller.go
- controller/doser/pump.go
- controller/doser/runner.go
- controller/lighting/controller.go
- controller/lighting/light.go
- controller/utils/pwm.go
- controller/utils/pwm_rpi.go
- controller/utils/pwm_test.go
- extract pwm interface
- extract light crud logic to its own file
> (chore). introduce rpi based pwm driver.

- jsx/ato/ato.jsx
- jsx/doser/pump.jsx
- jsx/lighting/light.jsx
- jsx/ph/probe.jsx
- jsx/temperature/sensor.jsx
- Make ph, ato, temperature sensor etc expandable in UI
> (chore)make all items expandable

- controller/macro/api.go
- controller/macro/macro.go
- jsx/app.jsx
- jsx/app.test.js
- jsx/camera/config.jsx
- jsx/connectors/inlets.jsx
- jsx/connectors/jacks.jsx
- jsx/connectors/outlets.jsx
- jsx/dashboard/main.jsx
- jsx/macro/macro.jsx
- jsx/macro/main.jsx
- jsx/macro/main.test.js
- jsx/main_panel.jsx
- jsx/main_panel.test.js
- jsx/ph/new.jsx
- jsx/redux/actions/admin.test.js
- jsx/redux/reducer.js
- jsx/utils/ajax.js
- jsx/utils/alert.js
- fix API error message ui
- make dashboard configuration button smaller
- show macro running state in ui
- extend smoke test to create macro
> (chore)Macro run ui improvement

- controller/macro/macro.go
- jsx/macro/wait_step_config.jsx
- Also dont fail macro if one of the step fails
> (bug)Convert duration of wait step (in macro) into integer before submitting

- jsx/sign_in.jsx
- package.json
Added Formik and Yup for validation.  Updated package.json dev dependencies.  Added required field validation to user name and password.
> Input validation for sign in and package.json clean up

- controller/settings.go
Streamline integration testing
```
make clean
make ui
make start-dev
node test/smoke.js
```
> (chore)enable all modules in dev mode

- .gitignore
- controller/equipment/controller_test.go
- controller/equipment/equipment.go
- webpack.config.js
Fixes #500 - Equipment updates leave outlets in inconsistent state.
Also added favicon to webpack
> Fixes #500 - Equipment updates leave outlets in inconsistent state.

- README.md
@Ranthalion @zekth let me know what you think about it. You guys have already done a lot of work
> (feat)add  michael and vince as maintainers

- jsx/app.jsx
- jsx/sign_in.jsx
- jsx/sign_in.test.js
> Unit fixes + Typo

- assets/sass/style.scss
- jsx/main_panel.jsx
> NavBar auto collapse fix

- jsx/configuration/configuration.test.js
- jsx/connectors/connectors.test.js
- jsx/connectors/inlet.jsx
- jsx/connectors/inlets.jsx
- jsx/connectors/jack.jsx
- jsx/connectors/jacks.jsx
- jsx/connectors/outlet.jsx
- jsx/connectors/outlets.jsx
- jsx/equipment/equipment.test.js
Improve Connectors panel,
deleting all calls to jQuery
Improving unit tests. Still needs some validations and Ui refactor
> Improve Connectors

- jsx/connectors/inlet.jsx
- jsx/connectors/inlets.jsx
- jsx/connectors/jack.jsx
- jsx/connectors/jacks.jsx
- jsx/connectors/outlet.jsx
- jsx/connectors/outlets.jsx
- jsx/main_panel.jsx
Make connectors UI in configuration usable on mobile
> Connectors enchancement

- jsx/temperature/edit_temperature.jsx
- jsx/temperature/edit_temperature.test.js
Fixes: https://github.com/reef-pi/reef-pi/issues/612
> (bug)fix typo in edit form logic

- jsx/ato/ato.jsx
- jsx/ato/ato_schema.jsx
- jsx/ato/edit_ato.jsx
- jsx/ato/new.jsx
- package-lock.json
Add notification UI to ATO
fixes #603
> Add notifications to ATO UI

- jsx/dashboard/main.jsx
> (bug)fix dashboard row and column layout

- jsx/lighting/channel.jsx
- jsx/lighting/light.jsx
- jsx/lighting/light_form.jsx
- jsx/lighting/light_schema.jsx
- jsx/lighting/lighting.test.js
- jsx/lighting/main.jsx
- jsx/lighting/validation.test.js
- jsx/ui_components/collapsible.jsx
- jsx/ui_components/collapsible.test.js
- test/light.js
- Allow edit of light name
- Refactor to use CollapsibleList
- Small code clean up for Collapsible
Preview at http://reef-pi.herokuapp.com/
fixes #609
> Add Light Name to edit form

- jsx/dashboard/main.jsx
- jsx/main_panel.jsx
- jsx/ui_components/error_boundary.jsx
- jsx/ui_components/error_boundary.test.js
Add ErrorBoundary around pages and around each chart.  It also adds the error to the notification center. 
Fixes #627
> Add ErrorBoundary

- jsx/redux/store.js
- jsx/telemetry/main.jsx
- jsx/telemetry/telmetry.test.js
fixes https://github.com/reef-pi/reef-pi/issues/524
> (bug)Performa telemetry form validation before submitting it instead of enable/disable click

- jsx/dashboard/config.jsx
- jsx/dashboard/main.jsx
- jsx/logCenter/main.jsx
- jsx/main_panel.jsx
> Forcing positive and scope related inputs

- controller/drivers/api.go
return from within `if` instead of else clause.
> (chore)Minor refactor of drivers code.

- controller/daemon/reef_pi.go
https://github.com/reef-pi/reef-pi/issues/667
> (chore)dont expire cookies

- controller/daemon/reef_pi.go
> Revert "(chore)dont expire cookies"

- jsx/redux/actions/ui.js
Macro tabs not showing timers, since timer list is not automatically loaded
> (bug)load timers as part of ui loading

- jsx/dashboard/main.jsx
use col instead of col6 in dashboard grid to support single column grids
> (bug) fix dashboard with 1 column

- jsx/telemetry/main.jsx
> fixing Telemetry

- jsx/doser/doser.test.js
- jsx/doser/main.jsx
- jsx/timers/main.jsx
- jsx/ui_components/collapsible.jsx
- jsx/ui_components/collapsible.test.js
Fixing https://github.com/reef-pi/reef-pi/issues/724
> Quick disable for timers and dosers

- controller/daemon/reef_pi.go
- controller/utils/tls.go
> Update expiration cookie each time the handler is successfully called

- commands/daemon_windows.go
> Change import to make window build works

- controller/daemon/loader.go
- controller/settings/settings.go
- jsx/configuration/configuration.test.js
- jsx/configuration/settings.jsx
- jsx/configuration/settings_schema.jsx
- package-lock.json
global pca9685 configuration is unused since pca9685 is now pluggable and the this configuration is available per driver basis
> [chore]Remove stale pca9684 configuration

- Makefile
- controller/daemon/auth.go
- Dont cache test
- Show remoteadd instead of referer in auth actions
> (chore)Fix auth logging

- Makefile
- controller/daemon/api.go
- webpack.config.js
ui asset delivery is broken in pi based deployment (debian)
> (bug)dont generate assets inside bin directory

- commands/manager_windows.go
Fix  go build for Windows.
Manager did not have a Windows implementation.  This PR adds a simple implementation to facilitate UI development on Windows machines.
> Chore: Add Windows implementation for manager.

- front-end/assets/translations/es.csv
- front-end/src/utils/translations/es.json
is that the translation into Spanish
> spanish translation

- Dockerfile
I just read an article from American Express Technology about security concerns raised when Dockerized application runs as root:
https://americanexpress.io/do-not-run-dockerized-applications-as-root/
Hence, I added a USER command to avoid running as root once the image is built. I am not entirely familiar with the use of Docker in this project, but I thought this would still be helpful to avoid security vulnerabilities.
> Add USER command to address security concern with Docker

- front-end/assets/translations/pt-pt.csv
add portuguese from Portugal language.
> Add portuguese language

- front-end/src/configuration/settings.jsx
- front-end/src/utils/translations/index.js
because https://github.com/reef-pi/reef-pi/pull/798 is merged. Activating it in the project
> active chinese

- front-end/src/ph/calibration_wizard.jsx
> Fix calibration error

- controller/modules/lighting/channel.go
- controller/modules/lighting/light.go
- front-end/src/lighting/light_schema.jsx
Instead of maintaining it via pwm_profile manager.
> (chore)Keep light channels' pwm profile as its own configuration

- front-end/src/redux/actions/ui.js
Timer module needs macro id/names .
> (chore)load macros if enabled

- .travis.yml
- Gopkg.lock
- Gopkg.toml
- controller/modules/doser/api_test.go
- controller/modules/doser/controller.go
- controller/modules/doser/pump.go
- controller/modules/doser/types.go
- controller/modules/lighting/channel.go
- controller/modules/lighting/light.go
- controller/modules/temperature/tc.go
- controller/modules/timer/api_test.go
- controller/modules/timer/controller.go
- controller/modules/timer/job.go
- controller/modules/timer/runner.go
- Update cron package
- Allow day of the week (Wed,Thu etc) and month of the year(Jan,Feb) fields in  timer specification
> (feat)Allow weekly and monthly schedule in timers

- front-end/src/timers/edit_timer.jsx
- front-end/src/timers/main.jsx
- front-end/src/timers/target.jsx
- front-end/src/timers/timer_form.jsx
- front-end/src/timers/timer_schema.jsx
- front-end/src/timers/timer_schema.test.js
@Ranthalion @zekth I could use some help here. I have taken a stab at the UI bits, but facing some validation issue. I think i am not able pass the validation properties to nested component (target). I have detailed the API in https://github.com/reef-pi/reef-pi/issues/830
> (chore)Timer ui

- front-end/assets/translations/nl.csv
> Add NL translation

- Makefile
- front-end/src/equipment/equipment.jsx
- package-lock.json
- package.json
> (bug)Fix equipment update hook

- front-end/src/configuration/configuration.test.js
- front-end/src/configuration/settings.jsx
Moves https to the address field and removes contradictory settings on change.  Fix is as described in issue comments.
Fixes #625
> Move protocol and reset if contradictory

- front-end/assets/translations/en.csv
- front-end/src/temperature/edit_temperature.jsx
- front-end/src/temperature/edit_temperature.test.js
- front-end/src/temperature/main.jsx
- front-end/src/temperature/new.jsx
- front-end/src/temperature/sensor.jsx
- front-end/src/temperature/temperature.test.js
- front-end/src/temperature/temperature_form.jsx
- front-end/src/temperature/temperature_schema.jsx
- front-end/test/tc.js
Implement hysteresis for temperature
fixes #857
> add homeostasis to temperature UI

- controller/homestatsis.go
- controller/modules/equipment/controller.go
- controller/modules/ph/probe.go
- controller/modules/temperature/tc.go
- front-end/src/ph/edit_ph.jsx
- front-end/src/ph/ph_form.jsx
- front-end/src/ph/ph_schema.jsx
- front-end/src/ph/ph_schema.test.js
And incorporate the same in temperature and ph module. Add ui support in ph module. Will add the same in temperature module after @Ranthalion has wrapped up temperature ui work
> (feat)Add hysteresis support in homeostasis module. 

- commands/db.go
- commands/main.go
- controller/connectors/analog_input.go
- controller/connectors/inlet.go
- controller/connectors/jack.go
- controller/connectors/outlet.go
- controller/daemon/error.go
- controller/drivers/main.go
- controller/modules/ato/ato.go
- controller/modules/camera/process.go
- controller/modules/doser/pump.go
- controller/modules/equipment/equipment.go
- controller/modules/lighting/light.go
- controller/modules/macro/macro.go
- controller/modules/ph/probe.go
- controller/modules/temperature/tc.go
- controller/modules/timer/job.go
- controller/storage/boltdb.go
- controller/storage/store.go
- controller/storage/store_test.go
- manager/instance.go
example:
```
reef-pi db list ato
reef-pi db show ato 1
reef-pi db delete ato 1
reef-pi db create ato -input ato.json
reef-pi db update ato 1 -input ato.json
```
> (feat)add sub-command to manage reef-pi database

- front-end/src/connectors/jack.jsx
> Bug fix remove jack

- front-end/src/lighting/auto_profile.jsx
- front-end/src/lighting/auto_profile.test.js
- front-end/src/lighting/channel.jsx
- front-end/src/lighting/fixed_profile.jsx
- front-end/src/lighting/light_form.jsx
- front-end/src/lighting/light_schema.jsx
- front-end/src/lighting/lighting.test.js
- front-end/src/lighting/main.jsx
- front-end/src/lighting/profile.jsx
- front-end/src/lighting/profile_selector.jsx
- front-end/src/lighting/validation.test.js
- front-end/test/light.js
Update Light UI to be compatible with new API.
Additional profiles are still pending, as well as manual/auto control.
> Update Lights UI to new API for version 3

- front-end/src/lighting/lighting.test.js
- front-end/src/lighting/main.jsx
- front-end/src/lighting/manual_light.jsx
- front-end/src/lighting/manual_light.test.js
- front-end/src/ui_components/collapsible.jsx
Add Manual/Auto functionality for light control.  
- A new button is added to switch between manual and auto contorll
- When in Manual mode, the Edit button is disabled. 
- If the channels are mixed the between manual and auto, the button switches to Auto
Auto Mode
Manual Mode
Mode switch modal
> Manual/Auto mode UI for lights

- front-end/src/telemetry/notification.jsx
@Ranthalion @zekth I have no clue why this fixes the bug, Advice,
> (bug) fix email to field under telemetry section

- front-end/src/utils/translations/index.js
> fix missing translation

- commands/db.go
- controller/storage/boltdb.go
- controller/storage/store.go
Fixes https://github.com/reef-pi/reef-pi/issues/909
> (feat)add support for listing buckets in db subcommand

- front-end/src/lighting/main.jsx
> Fix interval calculation for interval mode

- controller/pwm_profile/interval.go
- controller/pwm_profile/interval_test.go
fixes: https://github.com/reef-pi/reef-pi/issues/960
> (bug)add test and fix for interval profile index out of length issue

- front-end/src/connectors/analog_input.jsx
- front-end/src/connectors/inlet.jsx
- front-end/src/connectors/jack.jsx
- front-end/src/connectors/outlet.jsx
fixes https://github.com/reef-pi/reef-pi/issues/948
> (bug)fix connectors alignment

- controller/telemetry/health.go
- controller/telemetry/vcgencmd.go
- controller/telemetry/vcgencmd_test.go
use raspberry-pi vcgencmd command to detect Undervoltage  and expose it via health check sub-system. Error logging, alerting (in the event of under voltage ) and chart update still needs to be done
> (feat)Under voltage detector

- front-end/src/ph/calibrate.jsx
Fixes #990 
See https://www.reef2reef.com/threads/reef-pi-an-opensource-reef-tank-controller-based-on-raspberry-pi.289256/post-6804266
> Add step attribute to pH calibration for Firefox

- front-end/src/camera/gallery.jsx
- front-end/src/configuration/about.jsx
- front-end/src/configuration/display.jsx
- front-end/src/configuration/settings.jsx
- front-end/src/connectors/inlet_selector.jsx
- front-end/src/dashboard/component_selector.jsx
- front-end/src/dashboard/config.jsx
- front-end/src/dashboard/grid.jsx
- front-end/src/doser/main.jsx
- front-end/src/lighting/main.jsx
- front-end/src/redux/actions/ui.js
- front-end/src/summary.jsx
- front-end/src/ui_components/collapsible.test.js
- front-end/src/ui_components/collapsible_list.jsx
- front-end/src/ui_components/error_boundary.jsx
- package-lock.json
- package.json
- Also get rid of deprecated react lifecycle method usage
> (bug)Fix camera ui when no images are present

- controller/daemon/loader.go
- controller/modules/journal/api.go
- controller/modules/journal/parameter.go
- controller/modules/journal/subsystem.go
- controller/settings/capabilities.go
- controller/storage/boltdb.go
- controller/storage/store.go
- controller/storage/store_test.go
- front-end/src/journal/edit_journal.jsx
- front-end/src/journal/form.jsx
- front-end/src/journal/main.jsx
- front-end/src/journal/new.jsx
- front-end/src/journal/schema.js
- front-end/src/main_panel.jsx
- front-end/src/redux/actions/journal.js
- front-end/src/redux/actions/ui.js
- front-end/src/redux/reducer.js
- front-end/src/redux/store.js
"Journal" is a new module in reef-pi that will allow user to record manual entries such as alk testing values or ATO container fill up amount. It is aimed to help tracking manual workflow parameters (e.g water testing).
> (feat) Add Journal subsystem API implementation

- controller/drivers/factories.go
- controller/pwm_profile/factory_test.go
- controller/pwm_profile/lunar.go
- go.mod
- lunar profile computation panic when full moon is set to future date
- driver manager panic during un-initialized driver registration
> (bug) fix panic scenarios

- controller/drivers/factories.go
- go.mod
- go.sum
Add ADS1015 and ADS1115 drivers to UI to enable single ended analog channels. Fixes #1155
> Add ADS1X15 drivers to UI

- controller/modules/temperature/sensor.go
- controller/modules/temperature/sensor_test.go
Reject temperature readings <-55 or > 125, with up to 3 attempts.
fixes #1205
> Implement tc range rejection and retry

- .travis.yml
- package.json
> Add smoke test to travis

- front-end/src/lighting/auto_profile.jsx
- front-end/src/lighting/auto_profile.test.js
- front-end/src/lighting/fixed_profile.jsx
- front-end/src/lighting/lighting.test.js
- front-end/src/lighting/manual_light.jsx
- front-end/src/lighting/manual_light.test.js
- front-end/src/lighting/validation.test.js
- front-end/src/ui_components/percent.jsx
> Allow decimal values for lights

- front-end/src/ph/main.jsx
https://github.com/reef-pi/reef-pi/issues/1249
> (bug)fix ph hysteresis value passing in ui

- controller/connectors/outlet.go
- controller/connectors/outlet_test.go
- controller/daemon/loader.go
- controller/modules/ato/controlller_test.go
- controller/modules/doser/api_test.go
- controller/modules/equipment/controller.go
- controller/modules/equipment/controller_test.go
- controller/modules/lighting/api_test.go
- controller/modules/lighting/controller.go
- controller/modules/lighting/light.go
- controller/modules/temperature/api_test.go
- controller/modules/timer/api_test.go
travis to PR feedback seems to be broken.
> (bug)Fix master

- Dockerfile
- front-end/assets/translations/es.csv
Filled out missing sections of Spanish translation.  I also changed temporizador to cronomitro.  I think temporizador is used in Spain, and cronomitro is used in Latin America.
N/A
Enhance the Spanish translation
> Flush out Spanish translation

- controller/modules/temperature/tc.go
- front-end/src/temperature/edit_temperature.jsx
- front-end/src/temperature/main.jsx
- front-end/src/temperature/readings_chart.jsx
- front-end/src/temperature/temperature.test.js
- front-end/src/temperature/temperature_form.jsx
- front-end/src/temperature/temperature_schema.jsx
- front-end/src/temperature/temperature_schema.test.js
- go.mod
- go.sum
> (feat)Allow users to specify temperature chart configuration

- front-end/assets/translations/es.csv
Translate part of the untranslated Spanish words.
> Update Spanish translations

- front-end/assets/translations/es.csv
Issue: https://github.com/reef-pi/reef-pi/issues/1345
> More Spanish translations

- front-end/assets/translations/es.csv
Translate some translation keys to Spanish
> Spanish translations

- front-end/src/ato/edit_ato.jsx
- front-end/src/doser/calibration_modal.jsx
- front-end/src/doser/edit_doser.jsx
- front-end/src/doser/main.jsx
- front-end/src/drivers/driver.jsx
- front-end/src/drivers/driver_schema.jsx
- front-end/src/drivers/edit_driver.jsx
- front-end/src/drivers/new.jsx
- front-end/src/lighting/charts/diurnal.jsx
- front-end/src/lighting/main.jsx
- front-end/src/macro/edit_macro.jsx
- front-end/src/macro/wait_step.jsx
- front-end/src/ph/calibrate.jsx
- front-end/src/ph/calibration_wizard.jsx
- front-end/src/ph/edit_ph.jsx
- front-end/src/ph/main.jsx
- front-end/src/redux/actions/admin.js
- front-end/src/redux/actions/equipment.js
- front-end/src/temperature/main.jsx
- front-end/src/timers/target.jsx
- front-end/src/ui_components/collapsible.jsx
@zekth if possible, can you review the calibration modal changes? Im unsure if I'm doing this right (ref changes). I'll run smoke tests for validation
> (chore)Fix lint errors due to standard(js lint tool) upgrade

- .github/dependabot.yml
Change dependabot config to update GitHub actions
> Dependabot update GitHub actions

- controller/drivers/factories.go
- controller/drivers/factories_test.go
- go.mod
- go.sum
Add Tasmota driver factory in the factories register
> Add Tasmota driver

- front-end/src/ato/chart.jsx
- front-end/src/dashboard/blank_panel.jsx
- front-end/src/equipment/ctrl_panel.jsx
- front-end/src/ph/chart.jsx
- front-end/src/ph/edit_ph.jsx
- front-end/src/temperature/control_chart.jsx
- front-end/src/temperature/edit_temperature.jsx
- front-end/src/temperature/readings_chart.jsx
- package.json
- yarn.lock
- Remove module names (ato, ph, temperature) from chart headers
- Remove border and placeholder text from  blank panel
- Fix temp controller tooltip units
- Fix chart rendering for ph and temp charts on mobile devices
> (chore)various chart fixes

- controller/modules/ato/usage.go
> Revert "(bug)switch off ato target equipment while disabling by alert"

- package.json
A small cleanup / polish of the `package.json` file
> Cleanup of package.json

- .github/dependabot.yml
Allow dependabot update webpack-cli dependency
> dependabot allow update webpack-cli

- front-end/src/configuration/settings.jsx
- front-end/src/connectors/main.jsx
- front-end/src/drivers/driver.jsx
- front-end/src/drivers/main.jsx
Configuration:Settings:
corrected indentation of capabilities
added horizontal border between email notif. and Capabilities
Configuration:Connectors:
improved readability by borders between connector types
Configuration:Drivers:
driver 'rpi' is now handled by same <Driver ...> as all other drivers,
new property 'read_only' disallows all 'dangerous' operations,
this fixes appearance for 'rpi' in list of drivers
> UI cosmetics on configuration pages

- front-end/src/drivers/main.jsx
- front-end/src/instances/edit_instance.jsx
- front-end/src/instances/instance.jsx
- front-end/src/instances/instance_schema.js
- front-end/src/instances/main.jsx
- front-end/src/instances/view_instance.jsx
Generic validation messages & a few translations.
**Where is <Instance ...> used?**  
My hack to(temporarily) enable it, revealed
errors in the bound function names - fixed that, w/o a chance to test,
since the hack enabled the tab, which then showed several 404 errors.
>  Instance validation & missing translations

- Dockerfile
I'm having issues building reef-pi on an ARM mac. To workaround that I'm trying
to build under Docker. It appears this Dockerfile is old, and possibly not been
getting used. For example the node version it was using is very dated.
This updates the Dockerfile so at a minimum I am able to build the docker image
and within it build deb:
```
\# Build docker image and run it
$ docker build --platform=linux/amd64 -t debugreef
$ docker run -it debugreef bash
\# Within that image build reef-pi
$ make bin
$ make deb
...
Created package {:path=>"reef-pi-5.2-72-g7e5eeb6e.deb"}
```
> Fix the Dockerfile to allow building

- front-end/src/configuration/main.jsx
- front-end/src/main_panel.jsx
- front-end/src/summary.jsx
> (Chore) fix react router warning and duplicate route declaration

- controller/homeostatsis.go
**WIP NOTE**
This is a WIP. I haven't tested it locally yet with my actual reef-pi, nor do I know how to write an automated test for it. I don't see any controller tests when I did a quick check.
Sending as a WIP to give a heads-up on the fix.
**/WIP NOTE**
This updates the control code to flip as many heater/coolers as possible into the correct state when performing an action, regardless of what happens to some of them. For instance, if we're trying to heat the tank, we should try and turn on the heater regardless of what happens to the cooler. Similarly that same change applies to flipping on a cooler or turning everything off.
It's generally important this tries to flip everything to the proper state versus just reordering things. For instance, if we're trying to heat the tank we …
> Continue on partial failure in temp control

- controller/daemon/config.go
- controller/daemon/config_test.go
`ioutil.ReadFile` is deprecated in favour of `os.ReadFile`
> Update parse config

- controller/modules/lighting/controller_test.go
> (test) Add a light controller test

- commands/daemon.go
- controller/daemon/reef_pi.go
Capture error on stop controller when SIGTERM is received
> (chore) Capture errors on stop controller

- .github/workflows/go.yml
- controller/daemon/loader.go
- controller/subsystem_composite.go
- controller/subsystem_composite_test.go
Fix code coverage reports using `codecov/codecov-action`
> (ci) Recover code coverage reports
