reef-pi/reef-pi

commands/main.go
controller/api.go
controller/controller.go

reef-pi controller fails to start if lighting is enabled and pwm hardware is not configured or missing. This patch ensures that we start api server irrespective of whether any other subsystem starts or not

(bug)start api server even if i2c is disabled

---

Dockerfile

The resultant image can be used to iterate on the code base, especiall
on the front end code. Installs required NPM and Node versions, as
well as installing Go 1.10.
The Dockerfile is not used for Travis CI yet, as it requires a Ruby
install for the actual packaging work. I didn't want to lump over the
entire CI and test process in one shot.
The container doesn't currently "run" the service, though this could
be done. Its expected to be run in a shell environment at this stage.
Signed-off-by: Yann Ramin <atrus@stackworks.net>

Add a Dockerfile which contains a usable dev and build environment

---

controller/ato/ato.go
controller/ato/controlller.go
controller/ph/controller.go
controller/ph/probe.go
controller/temperature/controller.go
controller/temperature/tc.go

Current adafruit telemetry emission causes error when ph probe name or temperature sensor is updated, since the feed is only created during bootup and metric emission assume a feed with same name exist. Moving this logic to probe starting will fix all creation as well as update issues. We have to mention in the doc that users have to delete stale feeds (when sensors are deleted from reef-pi)

(bug)create feed when each sensor of probe is started

---

controller/equipment/controller.go

Currently reef-pi closes all GPIO during shutdown, this causes all equipment controller via power controller features will be stopped/ turned off during reef-pi reload. This is undesirable since a typical reef-pi upgrade process involves reloading reef-pi. This change set alters that behavior leaving the GPIO states as it is during shutdown/reloads.

(bug)don't close gpio upon shutdown

---

assets/sass/style.scss

Change z-index for div.drop-down menu.  This will set all button based dropdowns to appear above fixed footer.
Fixes #632

Fix component-selector to appear over footer

---

controller/ato/ato.go
controller/doser/pump.go
controller/health.go
controller/macro/subsystem.go
controller/ph/probe.go
controller/temperature/tc.go

To avoid bogus stats no found error before the first check interval. This causes bogus alerts in UI and confuses reef-pi users

(bug)preseed stats db everytime an entity created

---

jsx/configuration/settings.jsx
jsx/configuration/settings_schema.jsx
jsx/configuration/settings_schema.test.js

Users see NaN in rpi_pwm_freq and other fields where we do the parsing (string to int) . This changes the onChange validation to yup schema based validation, right before the update

(chore)add yup based validation instead of onChange parsing

---

package-lock.json
package.json

npm install was complaining:
```
added 2315 packages from 1480 contributors and audited 85781 packages in 86.634s
found 17 vulnerabilities (10 low, 5 high, 2 critical)
run `npm audit fix` to fix them, or `npm audit` for details
```
Updated package/package-lock files from the npm update.
The biggest bump was electron (why?), the rest were downstream pinned packages.
Validated basic UI actions (login, configure).

Update npm dependencies (security)

---

controller/modules/doser/pump.go
controller/modules/doser/runner.go
controller/modules/doser/types.go
jsx/doser/calibrate.jsx
jsx/doser/calibration_modal.jsx
jsx/doser/main.jsx

Referencing the conversation in https://github.com/reef-pi/reef-pi/pull/717
My goal is to be able to allow partial second dosing with a dosing pump (5.25 seconds). Currently the pump.regiment.duration is a "time.Duration". This field isn't really being used as a true time.Duration and as is represents a int64. I want to change it to be a float64 to allow decimal point precision.
Advantages to this way over the previous PR
1. Nanoseconds are not exposed through the API.
2. Not a breaking change (database and ui will work fine if I change it)
3. Much simpler change
A couple other thoughts. When I design an API I prefer to express the unit of a time field in its name rather than leaving it ambiguous. In this case I would change "duration" to "durationSeconds" so that any consumers of the API …

Changing DosingPump.regiment.duration to a float64

---

controller/drivers/main.go

Scenario:
- Create ph_board driver with invalid I2C address
- Call to register driver fails with error, not storing the driver in the drivers slice.
- UI shows driver instance, as it was still written to the
underlying store.
This fixes:
- Removing a driver which returned an error on registration from the
store (consistency)
- Allowing the removal of a driver which is in the store but not in
the loaded map (which could happen after the driver fails to
register due to removed hardware on reload)
- Closing the driver upon removal.

(bug)Don't register and remove zombie drivers

---

Gopkg.lock
controller/daemon/api.go
controller/daemon/prometheus.go
controller/daemon/reef_pi.go
controller/modules/ato/ato.go
controller/modules/lighting/light.go
controller/modules/ph/probe.go
controller/modules/temperature/control.go
controller/settings/settings.go
controller/telemetry/api.go
controller/telemetry/health.go
controller/telemetry/stats.go
controller/telemetry/telemetry_test.go
front-end/assets/translations/en.csv
front-end/src/configuration/settings.jsx
front-end/src/configuration/settings_schema.jsx

If enabled (Configuration -> Enable prometheus), reef-pill provide an api (/x/metrics) for prometheus to scrape go runtime metrics (gc, go routines, heap usage etc) as well as all normal telemetry (ato, ph, temperature etc).
This will allow users to run dedicated prometheus server for metrics storage and use grafana and any other tool to chart it.

(feat)Add Prometheus metrics integration

---

.travis.yml
Dockerfile
controller/utils/tls.go

Its 2019, time to keep up with the Go releases.
N/A
Stay on currently released and bugfixed versions of Go

(chore)Upgrade to go1.12 in CI

---

Gopkg.lock
controller/drivers/factories.go

- HS110 is a single outlet device with current monitoring capabilities, and HS300 is a multi-outlet device with current monitoring capabilities. Adding support for both devices in for outlet /equipment control and current monitoring .
- Current monitoring is implemented as ADC hal interface and can be visualized using the ph probe ui.

(feat)Add support for TpLink kasa hs110 and hs300 devices

---

.gitignore
controller/modules/macro/api.go
controller/modules/macro/macro.go
controller/modules/macro/macro_test.go
controller/modules/macro/step.go
controller/modules/macro/step_test.go
controller/modules/macro/subsystem.go

Macros can be reversible from now on. A boolean attribute "reversible" will be associated with every macro indicating users have explicitly designated them as reversible. From now on  macro run call will havea reverse flag, and when it is set to true and the macro is declared as reversible, reef-pi will execute the macro steps in reverse order and all target within each step will be reversed except the wait step, which acts same. Equipment, ato, timers ... all will be on or off depending upon how its normally configured.

(feat)make macros reversible

---

controller/daemon/api.go
controller/utils/doc.go

Add routes with documentations .Doc(req, resp)
```go
r.HandleFunc("/api/inlets", e.create).Methods("PUT").Doc(nil, new(Inlet))
```
To generate api.txt, invoke set environment variable REEF_PI_LIST_API on startup
```
REEF_PI_LIST_API=1 make start-dev
```
and that will automatically generate
```
PUT	/api/inlets
Input:
{
"id": "",
"name": "",
"pin": 0,
"equipment": "",
"reverse": false,
"driver": ""
}
```
We'll iterate from here on, by adding Doc calls to in all handler with appropirate req/resp types and then update the documentation format to markdown, or do some more fancy thing (default variable with example data?)
Replacing : https://github.com/reef-pi/reef-pi/pull/753

(feat) auto api documentation

---

front-end/assets/translations/en.csv
front-end/src/temperature/main.jsx

Defaults the temperature calibration modal to to the existing calibration point if it exists.
Fixes #884

Show current calibration point for temperature

---

front-end/src/ph/calibration_wizard.jsx

You probably remember this was changed to 1000ms, that was still too often for the Atlas circuit and errors appeared after 4 minutes of running. The absolute minimum appears to be 1070ms but I think 1500 guarantees there will be no timing issues. I have fully testing 1500ms and it works perfect.
While submitting a PR, please make sure the build is ok with Travis CI. If not fix it, and if you need help feel free to ask :blush: .
`Describe your Pull Request Feature or BugFix`
`If this PR fixes issues please list them for a better management of issues`
`Describe the reason and the context of the enhancement`

pH calibration check frequency

---

.travis.yml

Use nvm latest version for golang ci
Split ci between back end and front end
switch to npm ci to improve ci speed
Fixes #1207

Use nvm latest version for golang ci

---

Makefile
front-end/src/summary.jsx

users will be able to see the relevant api docs for their reef-pi version from controller itself under /assets/api.html path

(feat) serve api doc straight from the controller

---

controller/homestatsis.go
controller/modules/ph/probe.go
controller/modules/temperature/sensor.go
controller/telemetry/health.go
controller/telemetry/mailer_test.go
controller/telemetry/telemetry.go
controller/utils/number.go
controller/utils/number_test.go

Rename `TwoDecimal` method to `RoundToTwoDecimal` and move from telemetry package to utils package
None
`TwoDecimal` method is used outside the telemetry controller in other parts and uses the same test file that the `Mailer`, but the main motivation for my side is to start to known how reef-pi project works.

Rename TwoDecimal method and move to utils package

---

Dockerfile

While submitting a PR, please make sure the build is ok with Travis CI. If not fix it, and if you need help feel free to ask :blush: .
The current Dockerfile does not build.  From looking at the errors it looks like the version of go it is using is too old, and go 1.13 at least is required.  
NA
I wanted to test the UI out before buying components and a raspberry pi to run it.

update go version in docker file

---

controller/telemetry/telemetry.go
controller/telemetry/telemetry_test.go

Prometheus really only wants [a-zA-Z0-9_], previously we only removed
"-" but other characters would then proceeed to blow up if you use
"/", or any number of other characters. This restricts the subset to the
smaller set of allowed characters.

Sanitize prometheus metric names to a more strict filter

---

.github/workflows/deb.yml
go.mod
go.sum

Fix errors on GitHub action builds
```bash
Error: ../../../go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.3.2/netconn.go:26:2: missing go.sum entry for module providing package golang.org/x/net/proxy (imported by github.com/eclipse/paho.mqtt.golang); to add:
go get github.com/eclipse/paho.mqtt.golang@v1.3.2
make: *** [Makefile:59: vet] Error 1
```
Example: https://github.com/reef-pi/reef-pi/pull/1474/checks?check_run_id=2966404346
```
Error: ../../../go/pkg/mod/github.com/prometheus/procfs@v0.6.0/proc_maps.go:25:2: missing go.sum entry for module providing package golang.org/x/sys/unix (imported by github.com/shirou/gopsutil/mem); to add:
go get github.com/shirou/gopsutil/mem@v3.21.4+incompatible
```
Example: https://github.com/reef-pi/reef-pi/runs/3030550223?check_suite_focus=true

Fix GitHub action builds

---

.github/workflows/go.yml
.github/workflows/jest.yml
.github/workflows/translations.yml

Use Node version 14 in all of  the GitHub actions.

Syncronize all node version in GitHub actions

---

front-end/assets/translations/de.csv

mis-interpretation:  is "lower_function" the function to use when lower threshold is reached, or to reduce the controlled measurement?
Wasn't able to test the pH subsystem at time of translation. Test today showed German translation needs a swap of the two labels.

Fix: labels ph:upper_function and ph:lower_function swapped in German UI

---

.github/workflows/deb.yml
.github/workflows/jest.yml
.github/workflows/smoke_.yml
.github/workflows/translations.yml

Fix GitHub action caches to use `yarn.lock` file instead `package-lock.json` file.

Fix GitHub action caches

---

controller/modules/macro/macro.go

Make macro and steps both log with macro-subsystem.  Makes
logging consistent and easier to parse.

Make macro and steps logging consistent

---

.github/dependabot.yml

Clean dependabot ignores configurations for npm packages: [ignore option](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#specifying-dependencies-and-versions-to-ignore)

Clean dependabot configuration

---

front-end/src/ph/edit_ph.jsx
front-end/src/ph/ph_form.jsx
front-end/src/ph/ph_schema.jsx

When one of upperFunction or lowerFunction is 'nothing' the controller bails out.
No using '' instead of 'nothing'. tcs seems to work correctly with heater/cooler='nothing'.

fix: ph controller does not allow 'nothing'

---

front-end/src/configuration/configuration.test.js
front-end/src/configuration/main.jsx
front-end/src/main_panel.jsx
package.json
webpack.config.js
yarn.lock

This replaces the redux / custom management of the pages with a React Router
based version. The main impact of this is now you can directly go to urls
ala `/temperature` and it will render the appropriate page. The nav links
also point to this, which means you can also "open in new tab" to have
multiple reef pi tabs working at once.
I have tested this by going through the various pages and adding/deleting
things, playing with the forms, and navigating to various pages. It all
works for me. However I'm not sure if there's existing precedent for auto
testing this sort of change in this app.
I would recommend poking around at it a bit yourself as well to triple
check I didn't miss some behavior change, but it worked in my testing.
Implements #1780
Note while implementing this I found #1842, …

Support direct links to pages

---

front-end/src/configuration/configuration.test.js
front-end/src/configuration/main.jsx
front-end/src/main_panel.jsx
front-end/src/summary.jsx
package.json
webpack.config.js
yarn.lock

Link the Errors in footer to the Errors page
This is built on top of #1843. This doesn't combine the Log and Error screens,
but instead deep links to the error page.
I believe combining the Log and Errors screens will still be worthwhile, but
this is an easy improvement with the deep linking in place.
Tested just by pulling up the UI and seeing the link works.
Relates #1779
**Merge #1843 first**

Navigable errors link

---

front-end/src/configuration/capabilities.jsx
front-end/src/configuration/main.jsx
front-end/src/configuration/settings.jsx
front-end/src/connectors/connectors.test.js
front-end/src/connectors/main.jsx
front-end/src/main_panel.jsx
front-end/src/redux/actions/capabilities.js
front-end/src/redux/actions/ui.test.js
front-end/src/redux/store.js

Two separate commits fixing separate aspects of the connection screen data loading. These are technically issues even if you went to `http://reefpi/` and then quickly navigated to the other pages, but being able to jump to `http://reefpi/configuration/*` exposed it.
Relate to #1846

Add more data loading to config screens

---

front-end/src/temperature/temperature_schema.jsx
front-end/src/temperature/temperature_schema.test.js

Fixes #1836
TBH I'm not sure exactly what the behavior of hysteresis is, so I'm not
sure if there's cases where this validation is erroneous. However, this
fixes the bug where right now if you try and create a new temperature
with just a heater, it will fail validation without telling you why. Currently
it's requiring you to setup a cooler regardless, as outlined in #1836

Don't require a heater or cooler temp when they're disabled

---

front-end/src/doser/doser_schema.jsx
front-end/src/doser/doser_schema.test.js
front-end/src/lighting/lighting.test.js

This PR has a couple options in it. The final version is just deleting the regex completely, which I'm glad to see @ranjib suggested in #1850 because that seems like the most accurate solution.
87e3563e8c6ac0e0dc3e64f1d436389ad97ac30d updated the regex to support the more complicated (but not all) cron variants.
I also cleaned up a couple test warnings.

Fix doser regex

---

front-end/src/timers/timer_schema.jsx

Remove cron specification validation on the UI. its incorrect and inhibits users from entering */2 like specs. We have backend based validation already so this does not significantly risk saving wrong specs.

(chore)remove cron syntax validation

---

controller/storage/boltdb.go
controller/storage/store.go
controller/telemetry/api.go

After you have persisted telemetry settings, the UI no longer knows your creds.
This is good in that it avoids saved passwords getting returned out of the
backend, but it causes the UI to only allow updating telemetry if every time
you reenter in all the relevant passwords/tokens. That makes it very hard to
edit these later.
This is caused by the API blanking out those fields before returning them. That
is reasonable. However that leads to two issues. The first is the UI's
validation that token/password are filled in fails. The second is that if
you made the call to the backend, it'd then cause the database to be written
without those creds in it, losing them.
The current fix could be improved, as noted in the TODOs. However, given
right now the update flow has a major usability issue, I …

Fix telemetry creds flow

---

.github/workflows/deb.yml
.github/workflows/release.yml

Add a release workflow to automate the generation of release artifacts
This workflow is tested in my fork
- https://github.com/hectorespert/planted-pi/actions/runs/13224885524
- https://github.com/hectorespert/planted-pi/releases/tag/2025.1.1

(ci) Release Workflow
